// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Grifo.contexto;

#nullable disable

namespace Sistema_Grifo.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20240403235748_setima")]
    partial class setima
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_Grifo.Modelo.Configuracoesapp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("nud_Imp")
                        .HasColumnType("int");

                    b.Property<int>("nud_comissao")
                        .HasColumnType("int");

                    b.Property<int>("nud_margem_mao")
                        .HasColumnType("int");

                    b.Property<int>("nud_margem_material")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("configuracoesapp", (string)null);
                });

            modelBuilder.Entity("Sistema_Grifo.Modelo.Diversos", b =>
                {
                    b.Property<int>("CustoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustoID"));

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("valor_diversos")
                        .HasColumnType("real");

                    b.HasKey("CustoID");

                    b.ToTable("custosdiversos", (string)null);
                });

            modelBuilder.Entity("Sistema_Grifo.Modelo.Geralresult", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("valor_unidade")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("geralresult", (string)null);
                });

            modelBuilder.Entity("Sistema_Grifo.Modelo.MaoDeObra", b =>
                {
                    b.Property<int>("cargosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cargosID"));

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("Nome_cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("valor_cargo")
                        .HasColumnType("real");

                    b.HasKey("cargosID");

                    b.ToTable("cargos", (string)null);
                });

            modelBuilder.Entity("Sistema_Grifo.Modelo.Material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("valor_unidade")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("planilha", (string)null);
                });

            modelBuilder.Entity("Sistema_Grifo.Modelo.TabelaTemporaria", b =>
                {
                    b.Property<int>("temporarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("temporarioID"));

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<float>("valor")
                        .HasColumnType("real");

                    b.Property<float>("valorTotal")
                        .HasColumnType("real");

                    b.HasKey("temporarioID");

                    b.ToTable("tabelatemporaria", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
